# Generated by Django 6.0.6 on 2026-07-15 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Notificaciones push')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='Notificaciones por SMS')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='Notificaciones en app')),
                ('order_notifications', models.BooleanField(default=True, verbose_name='Notificaciones de pedidos')),
                ('promotion_notifications', models.BooleanField(default=True, verbose_name='Notificaciones de promociones')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='Notificaciones del sistema')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Inicio de horas silenciosas')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fin de horas silenciosas')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de notificaciones',
                'verbose_name_plural': 'Preferencias de notificaciones',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20, verbose_name='Tipo de dispositivo')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del dispositivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Último uso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de dispositivo',
                'verbose_name_plural': 'Tokens de dispositivos',
                'db_table': 'device_tokens',
                'unique_together': {('user', 'token')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_new', 'Nuevo pedido'), ('order_confirmed', 'Pedido confirmado'), ('order_preparing', 'Pedido en preparación'), ('order_ready', 'Pedido listo para entregar'), ('order_in_delivery', 'Pedido en camino'), ('order_delivered', 'Pedido entregado'), ('order_cancelled', 'Pedido cancelado'), ('order_rejected', 'Pedido rechazado'), ('order_rated', 'Pedido calificado'), ('promotion', 'Promoción especial'), ('discount', 'Descuento disponible'), ('system', 'Notificación del sistema'), ('reminder', 'Recordatorio'), ('update', 'Actualización de la plataforma'), ('welcome', 'Bienvenida'), ('verification', 'Verificación de cuenta'), ('password_changed', 'Contraseña cambiada')], max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Datos estructurados para la notificación', verbose_name='Datos adicionales')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivada')),
                ('priority', models.IntegerField(choices=[(0, 'Normal'), (1, 'Alta'), (2, 'Urgente')], default=0, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración de la notificación', null=True, verbose_name='Expira en')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order', verbose_name='Pedido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['type'], name='notificatio_type_8a8a78_idx')],
            },
        ),
    ]
