# Generated by Django 6.0.6 on 2026-07-11 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En preparación'), ('ready', 'Listo para entregar'), ('in_delivery', 'En camino'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('delivery_address', models.TextField(verbose_name='Dirección de entrega')),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('delivery_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('delivery_notes', models.TextField(blank=True, null=True, verbose_name='Notas de entrega')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('online', 'Pago en línea')], default='cash', max_length=20, verbose_name='Método de pago')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado')),
                ('preparing_at', models.DateTimeField(blank=True, null=True, verbose_name='En preparación')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Listo')),
                ('in_delivery_at', models.DateTimeField(blank=True, null=True, verbose_name='En camino')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado')),
                ('estimated_delivery_time', models.IntegerField(default=30, help_text='Tiempo estimado en minutos', verbose_name='Tiempo estimado de entrega')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('client_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación del cliente')),
                ('client_comment', models.TextField(blank=True, null=True, verbose_name='Comentario del cliente')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('delivery_person', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'delivery'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_delivery', to=settings.AUTH_USER_MODEL, verbose_name='Repartidor')),
                ('restaurant', models.ForeignKey(limit_choices_to={'user_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_restaurant', to=settings.AUTH_USER_MODEL, verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitud actual')),
                ('current_lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitud actual')),
                ('location_history', models.JSONField(blank=True, default=list, verbose_name='Historial de ubicaciones')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Seguimiento de entrega',
                'verbose_name_plural': 'Seguimientos de entregas',
                'db_table': 'delivery_tracking',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('selected_options', models.JSONField(blank=True, default=dict, verbose_name='Opciones seleccionadas')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item del pedido',
                'verbose_name_plural': 'Items del pedido',
                'db_table': 'order_items',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='orders_client__2e756d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'status'], name='orders_restaur_0aeb84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_person', 'status'], name='orders_deliver_7441d2_idx'),
        ),
    ]
