# Generated by Django 6.0.6 on 2026-07-20 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Distancia en km')),
                ('estimated_time', models.IntegerField(verbose_name='Tiempo estimado (minutos)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignado')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('delivery_person', models.ForeignKey(limit_choices_to={'user_type': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Repartidor')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Asignación de repartidor',
                'verbose_name_plural': 'Asignaciones de repartidores',
                'db_table': 'delivery_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
