# Generated by Django 6.0.6 on 2026-07-08 00:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio con descuento')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto alternativo de imagen')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('preparation_time', models.IntegerField(default=15, help_text='Tiempo de preparación en minutos', verbose_name='Tiempo de preparación')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vegetariano')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Vegano')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Sin gluten')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoría Global')),
                ('restaurant', models.ForeignKey(limit_choices_to={'user_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
                'ordering': ['restaurant', 'category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('option_type', models.CharField(choices=[('size', 'Tamaño'), ('flavor', 'Sabor'), ('extra', 'Extra'), ('custom', 'Personalizado')], default='custom', max_length=20, verbose_name='Tipo de opción')),
                ('is_required', models.BooleanField(default=False, verbose_name='Requerido')),
                ('max_choices', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de elecciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Opción de Producto',
                'verbose_name_plural': 'Opciones de Productos',
                'db_table': 'product_options',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(limit_choices_to={'user_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_categories', to=settings.AUTH_USER_MODEL, verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Categoría de Restaurante',
                'verbose_name_plural': 'Categorías de Restaurantes',
                'db_table': 'restaurant_categories',
                'ordering': ['restaurant', 'order', 'name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.restaurantcategory', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='ProductOptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Valor')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ajuste de precio')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por defecto')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='products.productoption', verbose_name='Opción')),
            ],
            options={
                'verbose_name': 'Opción de elección',
                'verbose_name_plural': 'Opciones de elección',
                'db_table': 'product_option_choices',
                'ordering': ['option', 'order', 'value'],
                'unique_together': {('option', 'value')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('restaurant', 'name')},
        ),
    ]
